SELECT RLS_ID
,MDM_ID
,MDM_CODE
,MDM_VALUE 
,LNG_ISO_CODE 
,LNG_ID 
FROM TD_MATRIX_DIMENSION 
INNER JOIN
(
	select MTR_ID
	,RLS_ID 
	,LNG_ISO_CODE 
	,LNG_ID 
	from TD_MATRIX 
	INNER JOIN TD_RELEASE 
	ON RLS_ID=MTR_RLS_ID
	AND MTR_DELETE_FLAG=0
	AND RLS_DELETE_FLAG=0
	INNER JOIN TS_LANGUAGE 
	ON MTR_LNG_ID=LNG_ID 
	AND LNG_DELETE_FLAG=0
) Q
ON Q.MTR_ID=MDM_MTR_ID 