select RLS_ID 
,MTR_ID  
,MTR_CODE
,MTR_TITLE 
,CPR_CODE 
,CPR_VALUE
,LNG_ISO_CODE 
,LNG_ID 
from TD_MATRIX 
INNER JOIN VW_RELEASE_LIVE_NOW 
ON MTR_ID=VRN_MTR_ID 
INNER JOIN TD_RELEASE 
ON RLS_ID=VRN_RLS_ID
INNER JOIN TS_LANGUAGE 
ON MTR_LNG_ID=LNG_ID 
AND LNG_DELETE_FLAG=0
INNER JOIN TS_COPYRIGHT 
ON MTR_CPR_ID=CPR_ID