select RLS_ID 
,MTR_ID  
,MTR_CODE
,MTR_TITLE 
,CPR_CODE 
,CPR_VALUE
,LNG_ISO_CODE 
,LNG_ID 
from TD_MATRIX 
INNER JOIN TD_RELEASE 
ON RLS_ID=MTR_RLS_ID
AND MTR_DELETE_FLAG=0
AND RLS_DELETE_FLAG=0
INNER JOIN TS_LANGUAGE 
ON MTR_LNG_ID=LNG_ID 
AND LNG_DELETE_FLAG=0
INNER JOIN TS_COPYRIGHT 
ON MTR_CPR_ID=CPR_ID