SELECT PRC_ID,
PRC_VALUE,'en' as LNG_ISO_CODE
FROM TD_PRODUCT
WHERE PRC_DELETE_FLAG=0
UNION
SELECT PLG_PRC_ID AS PRC_ID
,PLG_VALUE AS PRC_VALUE
,LNG_ISO_CODE
FROM TD_PRODUCT_LANGUAGE
INNER JOIN TS_LANGUAGE
ON LNG_ID=PLG_LNG_ID
AND LNG_DELETE_FLAG =0 