SELECT SBJ_ID
,SBJ_VALUE,'en' as LNG_ISO_CODE
FROM TD_SUBJECT 
WHERE SBJ_DELETE_FLAG=0
UNION
SELECT SLG_SBJ_ID AS SBJ_ID
,SLG_VALUE AS SBJ_VALUE
,LNG_ISO_CODE
FROM TD_SUBJECT_LANGUAGE 
INNER JOIN TS_LANGUAGE 
ON SLG_LNG_ID=LNG_ID
AND LNG_DELETE_FLAG =0 